language: node_js
node_js:
 - "0.12"
 - "4.0.0"

before_script:
  - npm install -g gulp
  - npm install -g typescript
  - npm install -g typings
script:
  - typings install
  - gulp copyfiles
  - gulp makedist
  - gulp test_ci